In [1]:
import pandas as pd
import numpy as np

In [14]:
income_df = pd.read_csv('income_evaluation_cat.csv',skipinitialspace=True)

In [15]:
for col in income_df.columns:
    print(col,':',income_df[col].unique(),'\n')
    

workclass : ['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' '?'
 'Self-emp-inc' 'Without-pay' 'Never-worked'] 

education : ['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th'] 

race : ['White' 'Black' 'Asian-Pac-Islander' 'Amer-Indian-Eskimo' 'Other'] 

gender : ['Male' 'Female'] 

income : ['<=50K' '>50K'] 



In [16]:
income_df.head()

workclass  education   race  gender income
0         State-gov  Bachelors  White    Male  <=50K
1  Self-emp-not-inc  Bachelors  White    Male  <=50K
2           Private    HS-grad  White    Male  <=50K
3           Private       11th  Black    Male  <=50K
4           Private  Bachelors  Black  Female  <=50K

In [41]:
X_in = ['Private','Bachelors','White','Female']

def my_nb(in_df,test_case):
    p_lt50 = len(in_df[in_df['income']=='<=50K'])/len(in_df)
    p_gt50 = len(in_df[in_df['income']=='>50K'])/len(in_df)
    
    p_work_lt = len(in_df.loc[(in_df['workclass']==X_in[0])].loc[in_df['income']=='<=50K'])/len(in_df)
    p_work_gt = len(in_df.loc[(in_df['workclass']==X_in[0])].loc[in_df['income']=='>50K'])/len(in_df)
    
    p_edu_lt = len(in_df.loc[(in_df['education']==X_in[1])].loc[in_df['income']=='<=50K'])/len(in_df)
    p_edu_gt = len(in_df.loc[(in_df['education']==X_in[1])].loc[in_df['income']=='>50K'])/len(in_df)
    
    p_race_lt = len(in_df.loc[(in_df['race']==X_in[2])].loc[in_df['income']=='<=50K'])/len(in_df)
    p_race_gt = len(in_df.loc[(in_df['race']==X_in[2])].loc[in_df['income']=='>50K'])/len(in_df)
    
    p_gen_lt = len(in_df.loc[(in_df['gender']==X_in[3])].loc[in_df['income']=='<=50K'])/len(in_df)
    p_gen_gt = len(in_df.loc[(in_df['gender']==X_in[3])].loc[in_df['income']=='>50K'])/len(in_df)
    
    p_dict = {}
    
    p_dict['<=50K'] = p_lt50*p_work_lt*p_edu_lt*p_race_lt*p_gen_lt
    p_dict['>50K'] = p_gt50*p_work_gt*p_edu_gt*p_race_gt*p_gen_gt
    
    max_key = '<=50K'
    max_val = p_dict['<=50K']
    
    for key in p_dict.keys():
        if p_dict[key]>max_val:
            max_key=key
            max_val = p_dict[key]
    
    return max_key

my_nb(income_df,X_in)
    


'<=50K'

In [49]:
from sklearn.preprocessing import LabelEncoder
income_scaled = pd.DataFrame(income_df,copy=True)
work_le = LabelEncoder()
edu_le = LabelEncoder()
race_le = LabelEncoder()
gender_le = LabelEncoder()
income_le = LabelEncoder()

income_scaled['workclass'] = work_le.fit_transform(income_scaled['workclass'])
income_scaled['education'] = edu_le.fit_transform(income_scaled['education'])
income_scaled['race'] = race_le.fit_transform(income_scaled['race'])
income_scaled['gender'] = gender_le.fit_transform(income_scaled['gender'])
income_scaled['income'] = income_le.fit_transform(income_scaled['income'])

income_scaled


workclass  education  race  gender  income
0              7          9     4       1       0
1              6          9     4       1       0
2              4         11     4       1       0
3              4          1     2       1       0
4              4          9     2       0       0
...          ...        ...   ...     ...     ...
32556          4          7     4       0       0
32557          4         11     4       1       1
32558          4         11     4       0       0
32559          4         11     4       1       0
32560          5         11     4       0       1

[32561 rows x 5 columns]

In [55]:
from sklearn.model_selection import train_test_split
X = income_scaled.iloc[:,:-1]
y = income_scaled.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3)

In [59]:
from sklearn.naive_bayes import CategoricalNB
cat_nb = CategoricalNB()

cat_nb.fit(X_train,y_train)
print('Train:',cat_nb.score(X_train,y_train))
print('Test:',cat_nb.score(X_test,y_test))

Train: 0.7827307827307828
Test: 0.7858532091309244


In [69]:
income_cont = pd.read_csv('income_evaluation_continuous.csv',skipinitialspace=True)
income_cont

age  education_num  hours_per_week income
0       39             13              40  <=50K
1       50             13              13  <=50K
2       38              9              40  <=50K
3       53              7              40  <=50K
4       28             13              40  <=50K
...    ...            ...             ...    ...
32556   27             12              38  <=50K
32557   40              9              40   >50K
32558   58              9              40  <=50K
32559   22              9              20  <=50K
32560   52              9              40   >50K

[32561 rows x 4 columns]

In [73]:
means = income_cont.groupby('income').mean()
means

age  education_num  hours_per_week
income                                          
<=50K   36.783738       9.595065       38.840210
>50K    44.249841      11.611657       45.473026

In [74]:
std = income_cont.groupby('income').std()
std

age  education_num  hours_per_week
income                                          
<=50K   14.020088       2.436147       12.318995
>50K    10.519028       2.385129       11.012971

In [82]:
from scipy.stats import norm


In [92]:
X_in = [30,10,45]
def nb_cont(in_df,X_in):
    means = in_df.groupby('income').mean()
    std = in_df.groupby('income').std()
    
    means_lt = means.loc['<=50K'].values
    means_gt = means.loc['>50K'].values
    
    sigma_lt = std.loc['<=50K'].values
    sigma_gt = std.loc['>50K'].values
    
    dens_lt = norm(means_lt,sigma_lt).pdf(X_in)
    dens_gt = norm(means_gt,sigma_gt).pdf(X_in)
    
    income_counts = in_df.income.value_counts()
    
    p_incomes = income_counts/sum(income_counts.values)
    
    p_lt = p_incomes[0]
    p_gt = p_incomes[1]
    
    post_dict = {}
    post_dict['<=50K'] = p_lt*np.prod(dens_lt)
    post_dict['>50K'] = p_gt*np.prod(dens_gt)
    
    max_key = '<=50K'
    max_val = post_dict['<=50K']
    
    for key in post_dict.keys():
        if post_dict[key]>max_val:
            max_key=key
            max_val = post_dict[key]
    
    return max_key

nb_cont(income_cont,X_in)

'<=50K'

In [109]:
from sklearn.preprocessing import StandardScaler, normalize
X = income_cont.iloc[:,:-1]
y = income_cont.iloc[:,-1]

print(X.head())
sc = StandardScaler()
X_std = sc.fit_transform(X)
print('\nStandardized:',X_std[:5])

X_norm = normalize(X)
print('\nNormalized:',X_norm[:5])



   age  education_num  hours_per_week
0   39             13              40
1   50             13              13
2   38              9              40
3   53              7              40
4   28             13              40

Standardized: [[ 0.03067056  1.13473876 -0.03542945]
 [ 0.83710898  1.13473876 -2.22215312]
 [-0.04264203 -0.42005962 -0.03542945]
 [ 1.05704673 -1.19745882 -0.03542945]
 [-0.77576787  1.13473876 -0.03542945]]

Normalized: [[0.67993384 0.22664461 0.69736804]
 [0.93856382 0.24402659 0.24402659]
 [0.67976467 0.16099689 0.71554175]
 [0.79379039 0.10484024 0.59908709]
 [0.55415675 0.25728706 0.79165249]]


In [111]:
X_train_std,X_test_std,y_train_std,y_test_std = train_test_split(X_std,y,test_size=25)

X_train_norm,X_test_norm,y_train_norm,y_test_norm = train_test_split(X_norm,y,test_size=25)

In [117]:
from sklearn.naive_bayes import GaussianNB

nb_std = GaussianNB()
nb_norm = GaussianNB()

nb_std.fit(X_train_std,y_train_std)
print('NB with Standard Scaler:')
print('Train:',nb_std.score(X_train_std,y_train_std))
print('Test:',nb_std.score(X_test_std,y_test_std))
print()

nb_norm.fit(X_train_norm,y_train_norm)
print('NB with normalized data:')
print('Train:',nb_norm.score(X_train_norm,y_train_norm))
print('Test:',nb_norm.score(X_test_norm,y_test_norm))

NB with Standard Scaler:
Train: 0.7997295303663634
Test: 0.84

NB with normalized data:
Train: 0.7591590853208754
Test: 0.8


In [267]:
true_df = pd.read_csv('True.csv',skipinitialspace=True)
true_df = pd.DataFrame({'title':true_df.title,'text':true_df.text,'news_type':True})
true_df.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text  news_type  
0  WASHINGTON (Reuters) - The head of a conservat...       True  
1  WASHINGTON (Reuters) - Transgender people will...       True  
2  WASHINGTON (Reuters) - The special counsel inv...       True  
3  WASHINGTON (Reuters) - Trump campaign adviser ...       True  
4  SEATTLE/WASHINGTON (Reuters) - President Donal...       True

In [268]:
fake_df = pd.read_csv('Fake.csv',skipinitialspace=True)
fake_df = pd.DataFrame({'title':fake_df.title,'text':fake_df.text,'news_type':False})
fake_df.head()

title  \
0  Donald Trump Sends Out Embarrassing New Year’s...   
1  Drunk Bragging Trump Staffer Started Russian C...   
2  Sheriff David Clarke Becomes An Internet Joke ...   
3  Trump Is So Obsessed He Even Has Obama’s Name ...   
4  Pope Francis Just Called Out Donald Trump Duri...   

                                                text  news_type  
0  Donald Trump just couldn t wish all Americans ...      False  
1  House Intelligence Committee Chairman Devin Nu...      False  
2  On Friday, it was revealed that former Milwauk...      False  
3  On Christmas day, Donald Trump announced that ...      False  
4  Pope Francis used his annual Christmas Day mes...      False

In [269]:
news_df = true_df.append(fake_df,ignore_index=True)

In [270]:
news_df['news'] = news_df.title+news_df.text

In [271]:
news_df.drop(['title','text'],axis=1,inplace=True)

In [272]:
news_df

news_type                                               news
0           True  As U.S. budget fight looms, Republicans flip t...
1           True  U.S. military to accept transgender recruits o...
2           True  Senior U.S. Republican senator: 'Let Mr. Muell...
3           True  FBI Russia probe helped by Australian diplomat...
4           True  Trump wants Postal Service to charge 'much mor...
...          ...                                                ...
44893      False  McPain: John McCain Furious That Iran Treated ...
44894      False  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...
44895      False  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...
44896      False  How to Blow $700 Million: Al Jazeera America F...
44897      False  10 U.S. Navy Sailors Held by Iranian Military ...

[44898 rows x 2 columns]

In [273]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, GridSearchCV
import re
import html
from nltk.corpus import stopwords
import string


In [274]:
sw = set(stopwords.words('english'))

In [275]:
def clean(text, stopwords):
    text = re.sub(r'<[^<>]*>',' ',text)
    text_list = text.split()
    text_words = list()
    
    punctuation = set(string.punctuation)
    
    for word in text_list:
        while len(word) > 0 and word[0] in punctuation:
            word = word[1:]
        while len(word) > 0 and word[-1] in punctuation:
            word = word[:-1]
        if len(word) > 0 and '/' not in word:
            if word.lower() not in stopwords:
                text_words.append(word.lower())
        clean_text = ' '.join(text_words)
        
    return clean_text

In [276]:
clean(news_df.news[305],sw)

'senate vote later wednesday work house tax bill mcconnellwashington reuters u.s senate majority leader mitch mcconnell said senate vote later wednesday whether send tax legislation conference hammer differences u.s house representatives’ version plan speaking chamber’s floor mcconnell also said congress later week would pass short-term continuing resolution measure continue funding federal government lawmakers work longer-term spending bill give dates'

In [277]:
news_df.dropna(inplace=True)

In [278]:
news_df.news = news_df.news.apply(clean,stopwords=sw)

In [279]:
mask = news_df.news.str.len() > 50
news_df = news_df[mask]

In [280]:
news_df.head()

news_type                                               news
0       True  u.s budget fight looms republicans flip fiscal...
1       True  u.s military accept transgender recruits monda...
2       True  senior u.s republican senator let mr mueller j...
3       True  fbi russia probe helped australian diplomat ti...
4       True  trump wants postal service charge much amazon ...

In [282]:
tfidf = TfidfVectorizer(ngram_range=(1,2),stop_words='english',min_df=10,max_features=None)

X = news_df.news
y=news_df.news_type

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=30)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [283]:
model = MultinomialNB()
model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [284]:
print('Train:',model.score(X_train_tfidf,y_train))
print('Test:',model.score(X_test_tfidf,y_test))

Train: 0.9580280416101311
Test: 0.9666666666666667


In [285]:
scores = cross_val_score(estimator=MultinomialNB(),X=X_train_tfidf,y=y_train,cv=5)
print('Avg cross val scores:',scores.mean())
print('Std cross val scores',scores.std())

Avg cross val scores: 0.9502035278154682
Std cross val scores 0.0024727158630188464


In [264]:
MultinomialNB().get_params()

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True}

In [292]:
pipe = Pipeline([('tfidf',TfidfVectorizer(stop_words='english')),('nb',MultinomialNB())])
param_grid = [{'tfidf__min_df':[5,10,20],'tfidf__ngram_range':[(1,1),(1,2)],'tfidf__norm':['l1','l2'],
              'nb__alpha':[0.5,1.0]}]

In [293]:
grid = GridSearchCV(estimator=pipe,param_grid=param_grid,cv=5)
grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('tfidf',
                                        TfidfVectorizer(stop_words='english')),
                                       ('nb', MultinomialNB())]),
             param_grid=[{'nb__alpha': [0.5, 1.0], 'tfidf__min_df': [5, 10, 20],
                          'tfidf__ngram_range': [(1, 1), (1, 2)],
                          'tfidf__norm': ['l1', 'l2']}])

In [294]:
grid.best_params_

{'nb__alpha': 0.5,
 'tfidf__min_df': 5,
 'tfidf__ngram_range': (1, 2),
 'tfidf__norm': 'l2'}

In [295]:
grid.score(X_train,y_train)

0.9679330619629127

In [296]:
reviews_df = pd.read_csv('IMDB Dataset.csv')

In [301]:
reviews_df.dropna(inplace=True)

In [304]:
reviews_df.review = reviews_df.review.apply(clean,stopwords=sw)

In [307]:
sentiment_le = LabelEncoder()
reviews_df.sentiment = sentiment_le.fit_transform(reviews_df.sentiment)

In [308]:
reviews_df.head()

review  sentiment
0  one reviewers mentioned watching 1 oz episode ...          1
1  wonderful little production filming technique ...          1
2  thought wonderful way spend time hot summer we...          1
3  basically there's family little boy jake think...          0
4  petter mattei's love time money visually stunn...          1

In [311]:
X = reviews_df.review
y = reviews_df.sentiment

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

tfidf = TfidfVectorizer(ngram_range=(1,2),stop_words='english',min_df=10,max_features=None)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [312]:
review_nb = MultinomialNB()

review_nb.fit(X_train_tfidf,y_train)

MultinomialNB()

In [313]:
print('Train:',review_nb.score(X_train_tfidf,y_train))
print('Test:',review_nb.score(X_test_tfidf,y_test))

Train: 0.9081866666666667
Test: 0.87664


In [317]:
review_pipe = Pipeline([('tfidf',TfidfVectorizer(stop_words='english')),('nb',MultinomialNB())])
review_param_grid = [{'tfidf__min_df':[5,10,20],'tfidf__ngram_range':[(1,1),(1,2)],'tfidf__norm':['l1','l2'],
              'nb__alpha':[0.5,1.0]}]

In [318]:
review_grid = GridSearchCV(estimator=review_pipe,param_grid=review_param_grid,cv=8)
review_grid.fit(X_train,y_train)

GridSearchCV(cv=8,
             estimator=Pipeline(steps=[('tfidf',
                                        TfidfVectorizer(stop_words='english')),
                                       ('nb', MultinomialNB())]),
             param_grid=[{'nb__alpha': [0.5, 1.0], 'tfidf__min_df': [5, 10, 20],
                          'tfidf__ngram_range': [(1, 1), (1, 2)],
                          'tfidf__norm': ['l1', 'l2']}])

In [319]:
review_grid.best_params_

{'nb__alpha': 0.5,
 'tfidf__min_df': 5,
 'tfidf__ngram_range': (1, 2),
 'tfidf__norm': 'l2'}

In [320]:
opt_pipe = Pipeline([('tfidf',TfidfVectorizer(stop_words='english',min_df=5,ngram_range=(1,2),norm='l2')),('nb',MultinomialNB(alpha=0.5))])
opt_pipe.fit(X_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(min_df=5, ngram_range=(1, 2),
                                 stop_words='english')),
                ('nb', MultinomialNB(alpha=0.5))])

In [321]:
print('Train:',opt_pipe.score(X_train,y_train))
print('Test:',opt_pipe.score(X_test,y_test))

Train: 0.9329066666666667
Test: 0.88264


In [322]:
opt_pipe.predict(['It was too slow and the actors are terrible'])

array([0])

In [323]:
opt_pipe.predict(['Lots of fun. Great plot and surprising end'])

array([1])